import com.github.javaparser.printer.concretesyntaxmodel.CsmElement.attribute

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `maven-publish`
    java
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("org.beryx.jlink") version "3.0.1"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.com.eatthepath.pushy)
    implementation(libs.com.fasterxml.jackson.core.jackson.databind)
    implementation(libs.org.apache.commons.commons.lang3)
    implementation(libs.org.bouncycastle.bcpkix.jdk15on)
    testImplementation(libs.junit.junit)
    testImplementation(libs.commons.io.commons.io)
}

application {
    mainModule = "pushy.console"
    mainClass = "com.eatthepath.pushy.console.PushyConsoleApplication"
}

group = "com.eatthepath"
version = "0.1-SNAPSHOT"
description = "pushy-console"

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "com.eatthepath.pushy.console.PushyConsoleApplication"
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

javafx {
    version = "22.0.1"
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.swing")
}

jlink {
    launcher {
        name = "pushy-console"
    }
    moduleName = "pushy.console"
    mergedModule {  }
    forceMerge("bcprov")
    forceMerge("bcpkix")
}
